baseURL: "https://trungtd.me/"
languageCode: "vi-VN"
defaultContentLanguage: "vi"
title: "Ti tỉ thứ linh tinh"
theme: "wisdom"

languages:
  vi:
    languageCode: "vi-VN"
    languageName: "Tiếng Việt"
    weight: 1

caches:
  images:
    dir: :cacheDir/images

params:
  languageCode: "vi"
  description: |
    Hiện mình đang làm các công việc của ~~(Data|ML|BE|Analytics) Engineer~~ Data Scientist.

    Nội dung blog này cũng tập trung vào Machine Learning nhưng thỉnh thoảng sẽ có chút review sách và game nữa nên mình nghĩ rằng nó giống nhật ký hơn là trang blog.

  mainSection: "posts"
  mainSectionTitle: "Bài viết mới nhất"
  titleCutting: true
  showAllPostsArchive: true
  mathjax: true
  showReadTime: false
  show_updated: true
  
  # SEO
  author: "Trung TD"
  keywords: ["Machine Learning", "Data Science", "AI", "Trí tuệ nhân tạo", "Học máy", "Blog công nghệ"]
  
  navlinks:
    - name: "about/"
      url: "about/"
    - name: "posts/"
      url: "posts/"
    - name: "projects/"
      url: "projects/"

  social:
    - name: "github"
      link: "https://github.com/niits"
    - name: "linkedin"
      link: "https://www.linkedin.com/in/niits/"

markup:
  goldmark:
    renderer:
      unsafe: true

ignoreLogs: ['warning-goldmark-raw-html']

services:
  googleAnalytics:
    ID: G-0378TMH2BM
