baseURL = 'https://trungtd.me/'
languageCode = 'vi-vn'
title = 'Ti tỉ thứ linh tinh'
theme = "cactus"

[params]
  description = "Machine Learning Engineer @ Sun*. \nNội dung blog này cũng tập trung vào Cloud Computing và Machine Learning nhưng sẽ ngắn hơn và ít formal hơn bên Viblo. Bên cạnh đó thì thỉnh thoảng sẽ có chút review sách và game nữa nên mình nghĩ rằng nó giống nhật ký hơn là trang blog :v"
  mainSection = "posts"
  mainSectionTitle = "Bài viết mới nhất"
  titleCutting = true
  showAllPostsArchive = true

  mathjax = true
  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

  [[params.social]]
    name = "github"
    link = "https://github.com/niits"

  [[params.social]]
    name = "email"
    link = "trungtdxz@gmail.com" # no need for "mailto:" at the start

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/niits/"

  [[menu.main]]
  name = "Bài viết"
  url = "/posts"
  weight = 1

  [[menu.main]]
  name = "Chủ đề"
  url = "/categories"
  weight = 2